### ISSUE TITLE
Symbol's value as variable is void: false

### ISSUE THREAD

**Issue by jwinder** [repl-electric/sonic-pi.el#11]
This stems from:

https://github.com/repl-electric/sonic-pi.el/blob/master/sonic-pi-osc.el#L8

I suspect this is the same issue as this comment https://github.com/repl-electric/sonic-pi.el/issues/10#issuecomment-141604854, but perhaps with a different version of emacs?

To temporarily remedy this situation, I added `(setq false nil)` to my config. I assume there was some reason for that `false` to exist, so I thought it was best to open an issue instead of a pull request.

**Comment by rrmdev** [comment]
I can confirm the issue. Sadly the fix proposed did not work in my case. I had to comment out the variable definition altogether from the sonic-pi-osc.el, and byte compile the modified source.

I do not understand the purpose of the variable definition, but it seems it could be removed.

**Comment by josephwilk** [comment]
Will take a look.

**Comment by rrmdev** [comment]
After a .emacs bankrupcy, I recently reconfigured sonic-pi.el.

Sadly, this issue is still present in the new setting. However...
This time the proposed solution by jwinder bypassed the issue.
i.e. adding (setq false nil) to the sonic-pi.el configuration.

Currently using:
GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.9) of 2015-03-21 on kissel, modified by Debian
sonic-pi.el 20150919.330 installed via package.el from the MELPA repository

**Comment by wdenton** [comment]
(setq false nil) got it working for me. I wrote #10, so I'll go close that.

**Comment by josephwilk** [comment]
Since this is a connivence I'll just remove the references and see how that goes.
